# Site settings
url: https://henrypark-96.github.io
title: MORISYSTEM
description: MORISYSTEM
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: MORISYSTEM
user_description: MORISYSTEM
email: anon@anon.com
twitter_username: MORISYSTEM
github_username:  MORISYSTEM
facebook_username:  MORISYSTEM

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
